# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: FernandoErazo.TrafficBar
PackageVersion: 1.0.1
InstallerType: inno
Scope: machine
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/xev777/TrafficBar/releases/download/v1.0.1/TrafficBar-Setup-1.0.1.exe
    InstallerSha256: B5B48CFE873124A337267AF34B491BAD9CB457C4EF3BB4582835B57E05C70C7E
    ProductCode: '{FA9D2CBD-4691-4E3A-AE9C-AB39DD6B2DE1}_is1'
ManifestType: installer
ManifestVersion: 1.6.0
